### ISSUE TITLE
Erreur TEST DAO

### ISSUE THREAD

**Issue by alchekroun** [alchekroun/M1_FRAMEWORK_EJB#21]
Branche : alextest
Classes impactées : TrainDAO, HeureDePassageDAO, TestTrainDAO

Bonjour,

Au cours de l'implémentation de nos tests unitaires nous sommes tombés sur deux erreurs qui nous empêchent d'avancer.
La première : 
Un problème d'injection, lorsque j'essaie d'injecter dans la classe TrainDAO, le dao suivant : HeureDePassageDAO j'obtiens une erreur

La seconde : 
Lorsque nous essayons de tester la méthode addArret(), nous avons une erreur "null pointer exception" dans la classe HeureDePassageDAO ligne 29.

Pourriez-vous nous aider à résoudre ce problème ?

Merci d'avance.

**Comment by nherbaut** [comment]
quelle erreur?

**Comment by alchekroun** [comment]
Les deux erreurs interviennent lorsque nous exécutons la classe TestTrainDAO.

Voici deux tests lancés avec le premier un @Inject (qui sans lui est totalement bloquant pour le reste des tests)
![1](https://user-images.githubusercontent.com/56997096/102923484-1d26e600-4490-11eb-8b4b-458f9319f88b.png)

Le second : 
![2](https://user-images.githubusercontent.com/56997096/102923486-1dbf7c80-4490-11eb-9cca-99a51ef47f32.png)

**Comment by nherbaut** [comment]
@alchekroun seams I fixed your CDI issues by adding the classes in Junit Weld configuration.

**Comment by nherbaut** [comment]
PR: https://github.com/alchekroun/M1_FRAMEWORK_EJB/pull/22

**Comment by alchekroun** [comment]
Merci pour votre aide, le test passe dorénavant.
