### ISSUE TITLE
Emplacement SeContainer

### ISSUE THREAD

**Issue by alchekroun** [alchekroun/M1_FRAMEWORK_EJB#27]
Branche : alexjms
Classes : Main; InfoCentrePublisher, InfoCentreServiceImpl

Bonjour Monsieur,

Lors de l'implémentation du pattern pubsub dans notre projet, un point bloquant est arrivé. Nous n'arrivons pas à comprendre où créer ce bout de code (cf copie d'écran 1). Car nous avons compris qu'il sert à créer l'objet mais surtout faire réagir le @PostConstruct init(). Pourriez-vous s'il vous plaît nous éclairer ?

Merci d'avance.

Copie d'écran 1 : 
![Capture d’écran 1](https://user-images.githubusercontent.com/56997096/103347157-801f0b00-4a96-11eb-8098-9d7a02735971.png)

Copie d'écran 2 : Exemple de notre implémentation du service InfoCentreServiceImpl dans le but d'envoyer un bulletin périodique des informations des trains.
![Capture d’écran 2](https://user-images.githubusercontent.com/56997096/103347394-2e2ab500-4a97-11eb-8342-0eda26f496a9.png)

Copie d'écran 3  et 4 : Notre classe InfoCentrePublisher 
![Capture d’écran 3](https://user-images.githubusercontent.com/56997096/103347304-e146de80-4a96-11eb-8570-0167af405cd7.png)

![Capture d’écran 4](https://user-images.githubusercontent.com/56997096/103347455-5adecc80-4a97-11eb-8b2f-2f443ff6301c.png)

**Comment by nherbaut** [comment]
https://github.com/alchekroun/M1_FRAMEWORK_EJB/pull/28

**Comment by nherbaut** [comment]
please check my PR and the companion review to better understand what was the problem. It seams to be working now:
1. launch the webapp
2. launch a jms subscriber
3. launch the client

results:
train info are show in the jms subscriber console

let me know if you need more help.
